import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { collection, query, where, onSnapshot, orderBy, } from "firebase/firestore";
import { db } from "../firebase";
import { Sparkles, ArrowLeft, X } from "lucide-react";
import Header from "./Header";
import Popup from "./Popup";
import "../styles/TrendingFashion.css";

const OCCASIONS = [
  "casual",
  "party",
  "office",
  "wedding",
  "festival",
  "date night",
];

const occasionMeta = {
  casual: { label: "Casual" },
  party: { label: "Party" },
  office: { label: "Office" },
  wedding: { label: "Wedding" },
  festival: { label: "Festival" },
  "date night": { label: "Date Night" },
};

const Trends = () => {
  const navigate = useNavigate();
  const [outfits, setOutfits] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedOccasion, setSelectedOccasion] = useState("all");
  const [selectedImage, setSelectedImage] = useState(null);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isProfileOpen, setIsProfileOpen] = useState(false);

  // ─────────────────────────────────────────
  // REAL-TIME FIREBASE LISTENER
  // ─────────────────────────────────────────
  useEffect(() => {
    const outfitsRef = collection(db, "outfits");
    const q = query(
      outfitsRef,
      where("isPublic", "==", true),
      orderBy("createdAt", "desc"),
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = [];
      snapshot.forEach((doc) => {
        data.push({ id: doc.id, ...doc.data() });
      });
      setOutfits(data);
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const filtered =
    selectedOccasion === "all"
      ? outfits
      : outfits.filter((o) => o.occasion?.toLowerCase() === selectedOccasion);

  return (
    <div className="home-container">
      <Header
        isMenuOpen={isMenuOpen}
        setIsMenuOpen={setIsMenuOpen}
        isProfileOpen={isProfileOpen}
        setIsProfileOpen={setIsProfileOpen}
      />

      <div className="trends-page">
        {/* PAGE TITLE */}
        <div className="trends-title-section">
          <div className="trends-title-row">
            <h1 className="trends-title">Trending Fashion</h1>
          </div>
          <p className="trends-subtitle">
            Real AI outfits generated by our community ✨
          </p>
        </div>

        <div className="divider">
          <span className="divider-icon">✧ ✦ ✧</span>
        </div>

        {/* OCCASION FILTER TABS */}
        <div className="filter-tabs">
          <button
            className={`filter-tab ${selectedOccasion === "all" ? "active" : ""}`}
            onClick={() => setSelectedOccasion("all")}
          >
            All
          </button>
          {OCCASIONS.map((occ) => (
            <button
              key={occ}
              className={`filter-tab ${selectedOccasion === occ ? "active" : ""}`}
              onClick={() => setSelectedOccasion(occ)}
            >
              {occasionMeta[occ]?.emoji} {occasionMeta[occ]?.label}
            </button>
          ))}
        </div>

        {/* LOADING */}
        {loading && (
          <div className="trends-empty">
            <p>✨ Loading trending looks...</p>
          </div>
        )}

        {/* EMPTY STATE */}
        {!loading && filtered.length === 0 && (
          <div className="trends-empty">
            <div className="empty-icon">👗</div>
            <h3>No looks here yet!</h3>
            <p>Be the first to generate and share an outfit.</p>
            <button
              className="go-chatbot-btn"
              onClick={() => navigate("/chatbot")}
            >
              <Sparkles size={16} /> Generate a Look
            </button>
          </div>
        )}

        {/* OUTFITS GRID */}
        {!loading && filtered.length > 0 && (
          <>
            <p className="trends-count">
              {filtered.length} Trending{filtered.length > 1 ? "s" : ""} Looks from the Community</p>

            <div className="trends-grid">
              {filtered.map((outfit) => (
                <div key={outfit.id} className="trend-card">
                  <div
                    className="trend-image-wrapper"
                    onClick={() => setSelectedImage(outfit.imageUrl)}
                  >
                    <img
                      src={outfit.imageUrl}
                      alt="Trending Outfit"
                      className="trend-image"
                    />
                    <div className="trend-badge">
                      {occasionMeta[outfit.occasion?.toLowerCase()]?.emoji ||
                        "✨"}{" "}
                      {occasionMeta[outfit.occasion?.toLowerCase()]?.label ||
                        outfit.occasion}
                    </div>
                  </div>
                  {/* Try This Look button removed */}
                </div>
              ))}
            </div>
          </>
        )}

        {/* BACK BUTTON */}
        <div className="trends-back">
          <button className="back-home-btn" onClick={() => navigate("/home")}>
            <ArrowLeft size={16} /> Back to Home
          </button>
        </div>
      </div>

      {/* FULLSCREEN MODAL */}
      {selectedImage && (
        <div className="image-modal" onClick={() => setSelectedImage(null)}>
          <button
            className="modal-close"
            onClick={() => setSelectedImage(null)}
          >
            <X size={24} color="white" />
          </button>
          <img src={selectedImage} alt="Full View" />
        </div>
      )}

      <Popup
        isMenuOpen={isMenuOpen}
        setIsMenuOpen={setIsMenuOpen}
        isProfileOpen={isProfileOpen}
        setIsProfileOpen={setIsProfileOpen}
      />
    </div>
  );
};

export default Trends;
